### ISSUE TITLE
Prune Klados v1.0 milestone

### ISSUE THREAD

**Issue by gaurav** [phyloref/klados#317]
- [x] Gaurav to take a first pass at pruning https://github.com/phyloref/klados/milestone/6
- [x] Any functionality that we describe in the paper should actually work (the goal for Klados v1.0).
- [x] For issues in the category "this is really important but not necessary for Klados v1.0":
  - Moved to Klados v1.1 (https://github.com/phyloref/klados/milestone/7)

Goals:
- Have a pruned milestone for Klados v1.0
- Review the high-priority list across all the issues and determine if any of that needs to be in the milestone

**Comment by gaurav** [comment]
I think we did this sufficiently by creating a [Klados v1.1 milestone](https://github.com/phyloref/klados/milestone/7) to work on after the manuscript has been submitted. I'm going to go ahead and close this, but please reopen if there's something I left out.
